print(f"Program starting.")
print(f"Estimate how many minutes you spent on programming...")
first_task = float(input("Insert minutes spent on first task: "))
second_task = float(input("Insert minutes spent on second task: "))
third_task = float(input("Insert minutes spent on third task: "))
fourth_task = float(input("Insert minutes spent on fourth task: "))
fifth_task = float(input("Insert minutes spent on fifth task: "))
sixth_task = float(input("Insert minutes spent on sixth task: "))
seventh_task = float(input("Insert minutes spent on seventh task: "))
total_task = (first_task+second_task+third_task+fourth_task+fifth_task+sixth_task+seventh_task)

print(f"A1_T2: {first_task:.0f}")
print(f"A2_T2: {second_task:.0f}")
print(f"A3_T2: {third_task:.0f}")
print(f"A4_T2: {fourth_task:.0f}")
print(f"A5_T2: {fifth_task:.0f}")
print(f"A5_T2: {sixth_task:.0f}")
print(f"A2_T7: {seventh_task:.0f}")

print(f"In total you spent {total_task:.0f} minutes on programming")
print(f"Average per task was {total_task/7:.2f} min and same rounded to the nearest integer {round(total_task/7)} min")
print(f"Program ending.")