print(f"Program starting.")
first_word = input("Insert first word: ")
second_word = input("Inserts second word: ")
print(f"1st word is {len(first_word)} characters long.")
print(f"2nd word is {len(second_word)} characters long.")
print(f"Words together makes one closed compound '{first_word+second_word}'.")
print(f"Program ending.")
