print("Program starting.")
print("")
start_val = int(input("Insert starting value: "))
stop_val = int(input("Insert stopping value: "))
print("")
print("Starting for-loop:")
for i in range(start_val, stop_val+1):
	print(i)
print("")
print("Program ending.")