print("Program starting.")
print("String comparisons")
first_word = input("Insert first word: ")
first_char = input("Insert a character: ")
if first_char in first_word: print(f"Word '{first_word}' contains character '{first_char}'")
else: print(f"Word '{first_word}' doesn't contain character '{first_char}'")
second_word = input("Insert second word: ")
if first_word < second_word: print(f"The first word '{first_word}' is before the second word '{second_word}' alphabetically.")
elif first_word > second_word: print(f"The second word '{second_word}' is before the first word '{first_word}' alphabetically")
else: print(f"Both inserted words are the same alphabetically, '{first_word}'")
print("Program ending.")