print("Program starting.")
print("This is a program with simple menu, where you can choose which operation the program performs.")
name = input("Before the menu, please insert your name: ")
print("")
print("Options:")
print("1 - Print welcome message")
print("0 - Exit")
user_input = int(input("Your choise: "))
if user_input == 1: print(f"Welcome {name}!")
elif user_input == 0: print("Exiting...")
else: print("Unknown option.")
print("")
print("Program ending.")