print("Program starting.")
print("Welcome to the unit converter program!")
print("Follow the menu instructions below.")
print("")
print("Options: ")
print("1 - Length")
print("2 - Weigth")
print("0 - Exit")
user_choice = float(input("Your choice: "))

if user_choice not in (0,1,2): print("Unknown option.")
elif user_choice == 0:
	print("")
	print("Exiting...")
elif user_choice == 1:
	print("")
	print("Length.options: ")
	print("1 - Meters to kilometers")
	print("2 - Kilometers to meters")
	print("0 - Exit")
	user_subchoice = float(input("Your choice: "))
	if user_subchoice not in (0, 1 ,2): print("Unknown option.")
	elif user_subchoice == 0: print("Exiting...")
	elif user_subchoice == 1:
		user_subchoice = float(input("Insert meters: "))
		print(f"{user_subchoice} m is {user_subchoice / 1000} km")
	elif user_subchoice == 2:
		user_subchoice = float(input("Insert kilometers: "))
		print(f"{user_subchoice} km is {user_subchoice * 1000} m")
elif user_choice == 2:
	print("")
	print("Weight.options: ")
	print("1 - Grams to pounds")
	print("2 - Pounds to grams")
	print("0 - Exit")
	user_subchoice = float(input("Your choice: "))
	if user_subchoice not in (0, 1, 2): print("Unknown option.")
	elif user_subchoice == 0: print("Exiting...")
	elif user_subchoice == 1:
		user_subchoice = float(input("Insert grams: "))
		print(f"{user_subchoice} g is {user_subchoice * 0.00220462:.4f} lb")
	elif user_subchoice == 2:
		user_subchoice = float(input("Insert pounds: "))
		print(f"{user_subchoice} lb is {user_subchoice * 453.59237:.1f}")
print("")
print("Program ending.")