print("Program starting.")
print("This is a program with simple menu, where you can choose which operation the program performs.")
user_name = input("Before the menu, please insert your name: ")
print("")
print("Options: ")
print("1 - Print welcome message")
print("2 - Print the name backwards")
print("3 - Print the first character")
print("4 - Show the amount of characters in the name")
print("0 - Exit")
user_input = int(input("Your choice: "))
if user_input == 1: print(f"Welcome {user_name}!")
elif user_input == 2: print(f'our name backwards is "{user_name[::-1]}"')
elif user_input == 3: print(f'The first character in name "{user_name}" is "{user_name[0:1:1]}"')
elif user_input == 4: print(f'There are {len(user_name)} characters in the name "{user_name}"')
elif user_input == 0: print("Exiting...")
else: print("Unknown input!")
print("")
print("Program ending.")
